### ISSUE TITLE
using the generated regex in the re module

### ISSUE THREAD

**Issue by EnricoGiampieri** [iogf/crocs#3]
Hi,

love the work you've done here.
I've tried to play with it a little bit, creating the regex and passing it to the **re** module.

The only way I've found to do it is to use the seed function like this:

    from crocs import *
    import re
    g = Group('X',Times(Include(Seq('0', '9')), 1, 2))
    e = Pattern(g, Times(Include(Seq('a', 'z')), 1, 3), g)
    regex_str = e.seed()[0]
    re.findall(regex_str, "X6zX6")

it this the official way to do it? I couldn't find any indication in the wiki about this. Wouldn't a property be more appropriate to access it, something like **e.regex** or similar?

**Comment by iogf** [comment]
Yes, thats the official way of doing that, the second argument returned by seed is a valid input.

**Comment by EnricoGiampieri** [comment]
I would suggest to use a more expressive way to do that, and to document it explicitly.
Being the main use target (for someone like me) of using such a library, it feels too contrived.

it would be sufficient to do something like:

    class Pattern(...):
        ...
        @property
        def regex(self):
            return self.seed()[0]
        ....

**Comment by iogf** [comment]
I'll refactor some functions and implement in a better way the to_regex, in this way.
